### ISSUE TITLE
Advanced Input Example Bug (Graphx Version)

### ISSUE THREAD

**Issue by jshin313** [Captain-Calc/textioc#2]
Hi. When I type the letter "T" in the second input box for the advanced input example, it blacks out the input box. I don't think this occurs for the fontlib version (I didn't thoroughly test). After the input box gets blacked out, [clear] or [delete] has no visible effect.

https://cdn.discordapp.com/attachments/725408711262077027/745836194411184138/lettert.png

**Comment by captain-calc** [comment]
Yes, that is a known bug although I thought I had fixed it. It happens because the input function gets the color of the pixel at the current cursor x-y position to set the erasing color. The letter 'T' in the GraphX font is wider than the others and happens to paint the pixel tested, thus setting the erasing color to black. I will review my code to see where the issue is. Thanks for reporting the bug!

**Comment by captain-calc** [comment]
Since the textio_Input() function no longer exists in the current version of TextIOC, I think this issue can be closed safely.
